package com.dwurdy.straja.domain.model;

public enum DocumentType {
    RECRUITMENT_ORDER,
    APPOINTMENT_ORDER,
    MISSION_ORDER,
    PROMOTION_APPLICATION,
    EQUIPMENT_RETURN_PROOF,
    COMPLAINT,
    REPORT,
    OFFICIAL_RESPONSE,
    MOBILIZATION_ORDER,
    EQUIPMENT_ORDER,
    REQUISITION_TICKET,
    MATERIAL_VOUCHER,
    RATION_VOUCHER,
    REPAIR_VOUCHER
}
