"""Round-2 refusal map additions — appends entries to refusal-map.py MAP.
Run: python tools/refusal-map-additions.py  (from repo root)
Idempotent: skips if marker present.
"""
import io, sys

PATH = "tools/refusal-map.py"
MARKER = "# --- CustodyService state/item gates"

ADDITIONS = '''

MAP.update({
    # --- CustodyService state/item gates ---------------------------------------
    "%s este deja încătușat.": ("straja.custody.already_cuffed",
        "straja.remedy.retry", "is already cuffed."),
    "%s este deja legat.": ("straja.custody.already_bound",
        "straja.remedy.retry", "is already bound."),
    "Ținta are deja o cerere în așteptare.": ("straja.custody.request_pending",
        "straja.remedy.wait", "The target already has a pending request."),
    "Ești deja încătușat.": ("straja.custody.self_cuffed",
        "straja.remedy.retry", "You are already cuffed."),
    "Alege persoana încătușată online.": ("straja.custody.pick_cuffed_online",
        "straja.remedy.fix_retry", "Pick a cuffed person who is online."),
    "Alege persoana încătușată.": ("straja.custody.pick_cuffed",
        "straja.remedy.fix_retry", "Pick a cuffed person."),
    "Alege un alt jucător.": ("straja.custody.pick_other",
        "straja.remedy.fix_retry", "Pick another player."),
    "Cătușele sunt disponibile de la rangul Străjer în sus.": ("straja.custody.cuffs_rank",
        "straja.remedy.instructor", "Handcuffs are available from Străjer rank up."),
    "Ține Frânghia în mâna principală.": ("straja.custody.hold_rope",
        "straja.remedy.fix_retry", "Hold the Rope in your main hand."),
    "Ține Sacul de Captiv în mâna principală.": ("straja.custody.hold_bag",
        "straja.remedy.fix_retry", "Hold the Captive Bag in your main hand."),
    "%s are deja sacul pe cap.": ("straja.custody.already_bagged",
        "straja.remedy.retry", "already has the bag on their head."),
    "Ținta este deja transportată.": ("straja.custody.already_carried",
        "straja.remedy.retry", "The target is already being carried."),
    "%s de Poliție se folosește de la rangul Străjer în sus.": ("straja.custody.weapon_rank",
        "straja.remedy.instructor", "is used from Străjer rank up."),
    # --- ArchiveService limits --------------------------------------------------
    "Ai atins limita de dosare pentru acest proprietar.": ("straja.archive.owner_limit",
        "straja.remedy.wait", "You reached the dossier limit for this owner."),
    "Dosarul a atins limita de foi.": ("straja.archive.sheets_limit",
        "straja.remedy.wait", "The dossier reached its sheet limit."),
    "Scrie conținutul înainte de semnare.": ("straja.archive.write_first",
        "straja.remedy.fix_retry", "Write the content before signing."),
    "Dosarul a atins limita de înregistrări de catalog.": ("straja.archive.catalog_limit",
        "straja.remedy.wait", "The dossier reached its catalog entry limit."),
    "Documentul %s i-a fost deja emis lui %s.": ("straja.archive.already_issued",
        "straja.remedy.fix_retry", "Document %s was already issued to %s."),
    # --- BoloService ------------------------------------------------------------
    "Motivul BOLO este obligatoriu și are o lungime limitată.": ("straja.bolo.reason_required",
        "straja.remedy.fix_retry", "The BOLO reason is required and length-limited."),
    "Subiectul are deja prea multe BOLO-uri active.": ("straja.bolo.too_many",
        "straja.remedy.wait", "The subject already has too many active BOLOs."),
    # --- EmergencyService ---------------------------------------------------------
    "Starea de urgență este deja activă (×%s plată, %s runde obligatorii).": ("straja.emergency.already_active",
        "straja.remedy.fix_retry", "A state of emergency is already active (×%s pay, %s mandatory rounds)."),
    # --- EvidenceService -----------------------------------------------------------
    "Doar un Străjer activ și operațional poate percheziționa.": ("straja.evidence.search_guard",
        "straja.remedy.duty", "Only an active on-duty Străjer can search."),
    "Ținta nu este disponibilă.": ("straja.evidence.target_unavailable",
        "straja.remedy.retry", "The target is not available."),
    "Nu există un context valid de percheziție.": ("straja.evidence.no_context",
        "straja.remedy.retry", "There is no valid search context."),
    # --- FineService -----------------------------------------------------------------
    "Ține Registrul de Amenzi în inventar și fii în serviciu.": ("straja.fine.hold_ledger",
        "straja.remedy.duty", "Hold the Fines Ledger in your inventory and be on duty."),
    "Nu ai formular de amendă.": ("straja.fine.no_form",
        "straja.remedy.fix_retry", "You have no fine form."),
    "Amenda are deja o contestație înregistrată.": ("straja.fine.appeal_exists",
        "straja.remedy.retry", "The fine already has a registered appeal."),
    "Folosește uphold, reduce <tarif-standard> sau void.": ("straja.fine.decision_invalid",
        "straja.remedy.fix_retry", "Use uphold, reduce <standard-fee> or void."),
    "Misiunile de arestare sunt disponibile de la rangul Străjer în sus.": ("straja.fine.arrest_rank",
        "straja.remedy.instructor", "Arrest missions are available from Străjer rank up."),
    "Ești deja în echipa acestei misiuni.": ("straja.fine.already_in_mission",
        "straja.remedy.retry", "You are already on this mission's team."),
    "Ținta are deja o sentință activă.": ("straja.fine.sentence_active",
        "straja.remedy.fix_retry", "The target already has an active sentence."),
    "Recompensa pentru dosarul %s a fost deja plătită.": ("straja.fine.reward_paid",
        "straja.remedy.retry", "The bounty for case %s was already paid."),
    "Ai atins limita zilnică de recompense pentru arestări.": ("straja.fine.daily_reward_cap",
        "straja.remedy.wait", "You reached the daily arrest-bounty limit."),
    "Există deja un mandat de audiere activ pentru această țintă.": ("straja.fine.warrant_exists",
        "straja.remedy.retry", "An active hearing warrant already exists for this target."),
    # --- GuardService commissioner/state gates ------------------------------------
    "Ești deja %s.": ("straja.duty.already_rank",
        "straja.remedy.instructor", "You are already %s."),
    "Ai deja o invitație de la Comisar — prezintă-te direct la Instructor pentru examen.": ("straja.duty.has_invite",
        "straja.remedy.instructor", "You already have the Commissioner's invitation — go straight to the Instructor for the exam."),
    "Cererea ta este deja înregistrată. Prezintă-te la Instructor pentru examen.": ("straja.duty.request_pending",
        "straja.remedy.instructor", "Your application is already registered. Go to the Instructor for the exam."),
    "Răspuns greșit. Modulul rămâne disponibil după cooldown.": ("straja.duty.quiz_wrong",
        "straja.remedy.wait", "Wrong answer. The module stays available after the cooldown."),
    "Ai deja Manualul de instruire în inventar.": ("straja.duty.manual_owned",
        "straja.remedy.fix_retry", "You already have the Training Manual in your inventory."),
    "Promovările sunt decizia finală a Comisarului.": ("straja.duty.promote_comisar",
        "straja.remedy.ask_comisar", "Promotions are the Commissioner's final call."),
    "Retrogradările sunt decizia Comisarului.": ("straja.duty.demote_comisar",
        "straja.remedy.ask_comisar", "Demotions are the Commissioner's call."),
    "Ținta este deja Civil.": ("straja.duty.target_civilian",
        "straja.remedy.fix_retry", "The target is already a Civilian."),
    "Suspendările sunt decizia Comisarului.": ("straja.duty.suspend_comisar",
        "straja.remedy.ask_comisar", "Suspensions are the Commissioner's call."),
    "Autorizarea directă este decizia Comisarului.": ("straja.duty.authorize_comisar",
        "straja.remedy.ask_comisar", "Direct authorization is the Commissioner's call."),
    "%s are deja o fișă Straja — folosește promovare/reintegrare.": ("straja.duty.has_record",
        "straja.remedy.fix_retry", "%s already has a Straja record — use promote/reinstate."),
    "Reintegrarea este decizia Comisarului.": ("straja.duty.reinstate_comisar",
        "straja.remedy.ask_comisar", "Reinstatement is the Commissioner's call."),
    "Îndepărtarea din Strajă este decizia Comisarului.": ("straja.duty.fire_comisar",
        "straja.remedy.ask_comisar", "Removal from Straja is the Commissioner's call."),
    "Revenirea este disponibilă peste %s.": ("straja.duty.return_cooldown",
        "straja.remedy.wait", "Return is available in %s."),
    "Hrana de serviciu este disponibilă de la Stagiar.": ("straja.duty.food_rank",
        "straja.remedy.instructor", "Duty food is available from Stagiar up."),
    "Kitul este disponibil de la Stagiar.": ("straja.duty.kit_rank",
        "straja.remedy.instructor", "The kit is available from Stagiar up."),
    "Kitul pentru rangul curent a fost deja ridicat.": ("straja.duty.kit_claimed",
        "straja.remedy.wait", "The kit for your current rank was already claimed."),
    "Limita de %s checkpoint-uri a fost atinsă.": ("straja.duty.checkpoint_limit",
        "straja.remedy.fix_retry", "The limit of %s checkpoints was reached."),
    "Folosește un checkpoint valid și un timp întreg între %s și %s minute.": ("straja.duty.checkpoint_invalid",
        "straja.remedy.fix_retry", "Use a valid checkpoint and a whole time between %s and %s minutes."),
    "Demisie în așteptare. Semnarea este disponibilă peste %s.": ("straja.duty.resign_wait",
        "straja.remedy.wait", "Resignation pending. Signing is available in %s."),
    # --- IdentityCardService ------------------------------------------------------
    "Jucătorul are deja buletinul activ %s.": ("straja.idcard.already_active",
        "straja.remedy.fix_retry", "The player already has active ID card %s."),
    "Registrul de buletine este epuizat.": ("straja.idcard.exhausted",
        "straja.remedy.wait", "The ID-card registry is exhausted."),
    "Buletinul %s era deja revocat.": ("straja.idcard.already_revoked",
        "straja.remedy.fix_retry", "ID card %s was already revoked."),
    # --- IncidentService ------------------------------------------------------------
    "Ai raportat deja un incident recent. Așteaptă înainte de a trimite altul.": ("straja.incident.rate_limited",
        "straja.remedy.wait", "You already reported an incident recently. Wait before sending another."),
    "Ai atins limita de incidente active raportate de tine.": ("straja.incident.active_limit",
        "straja.remedy.wait", "You reached the limit of active incidents reported by you."),
    "Fluierul se reîncarcă. Mai așteaptă %s secunde.": ("straja.incident.whistle_cooldown",
        "straja.remedy.wait", "The whistle is recharging. Wait %s more seconds."),
    "Incidentul este deja preluat de %s.": ("straja.incident.already_taken",
        "straja.remedy.retry", "The incident is already handled by %s."),
    # --- MissionService direct gates -------------------------------------------------
    "Scrie obiectivul misiunii după timpul de început.": ("straja.mission.objective_after_start",
        "straja.remedy.fix_retry", "Write the mission objective after the start time."),
    "Scrie ordinul înainte să configurezi participanții.": ("straja.mission.write_order_first",
        "straja.remedy.fix_retry", "Write the order before configuring participants."),
    "Semnează ordinul înainte să-l împachetezi.": ("straja.mission.sign_first",
        "straja.remedy.fix_retry", "Sign the order before packing it."),
    "Ține Carnetul de Misiuni în mâna principală.": ("straja.mission.hold_ledger",
        "straja.remedy.fix_retry", "Hold the Mission Ledger in your main hand."),
    "Folosește timpul între %s și %s minute și descrie obiectivul.": ("straja.mission.time_range",
        "straja.remedy.fix_retry", "Use a time between %s and %s minutes and describe the objective."),
    "Ținta are deja prea multe misiuni active.": ("straja.mission.target_busy",
        "straja.remedy.wait", "The target already has too many active missions."),
    "Bugetul zilnic de recompense al emitentului este epuizat (%s/%s monede).": ("straja.mission.budget_exhausted",
        "straja.remedy.wait", "The issuer's daily reward budget is exhausted (%s/%s coins)."),
    "Acest ordin a atins limita de %s copii. Scrie un ordin nou pentru alte predări.": ("straja.mission.order_copies",
        "straja.remedy.fix_retry", "This order reached its limit of %s copies. Write a new order for other hand-ins."),
    "Fondul ordinului este epuizat: mai sunt %s monede disponibile.": ("straja.mission.order_funds",
        "straja.remedy.wait", "The order's fund is exhausted: %s coins remain available."),
    "Misiunea a atins limita de %s participanți.": ("straja.mission.limit_arg",
        "straja.remedy.wait", "The mission reached its limit of %s participants."),
    "Jucătorul este deja invitat sau participant.": ("straja.mission.already_invited",
        "straja.remedy.retry", "The player is already invited or a participant."),
    "Participantul are deja prea multe misiuni active.": ("straja.mission.participant_busy",
        "straja.remedy.wait", "The participant already has too many active missions."),
    "Ești deja participant în misiunea #%s.": ("straja.mission.already_member",
        "straja.remedy.retry", "You are already a participant in mission #%s."),
    "Misiunea a atins limita de participanți.": ("straja.mission.full",
        "straja.remedy.wait", "The mission reached its participant limit."),
    "Scrie raportul misiunii.": ("straja.mission.write_report",
        "straja.remedy.fix_retry", "Write the mission report."),
    "Cota ta din recompensa misiunii a fost deja plătită.": ("straja.mission.share_paid",
        "straja.remedy.retry", "Your share of the mission reward was already paid."),
    "Misiunea poate fi acceptată de la: %s.": ("straja.mission.accept_from",
        "straja.remedy.fix_retry", "The mission can be accepted from: %s."),
    # --- MissionService helper returns (start parse / template validation) ----------
    "Folosește „acum” sau data în format YYYY-MM-DDTHH:MM.": ("straja.mission.start_format",
        "straja.remedy.fix_retry", "Use \\"now\\" or the date in YYYY-MM-DDTHH:MM format."),
    "Data de început nu este validă.": ("straja.mission.start_invalid",
        "straja.remedy.fix_retry", "The start date is not valid."),
    "Data de început trebuie să fie acum sau în viitor.": ("straja.mission.start_past",
        "straja.remedy.fix_retry", "The start date must be now or in the future."),
    "Data de început poate fi programată la maximum %s zile în viitor.": ("straja.mission.start_horizon",
        "straja.remedy.fix_retry", "The start date can be scheduled at most %s days ahead."),
    "Numele trebuie să aibă 1-60 caractere.": ("straja.mission.tpl_name",
        "straja.remedy.fix_retry", "The name must be 1-60 characters."),
    "Rangul minim trebuie să fie 1-4.": ("straja.mission.tpl_rank",
        "straja.remedy.fix_retry", "The minimum rank must be 1-4."),
    "Orele estimate trebuie să fie între 0 și 24.": ("straja.mission.tpl_hours",
        "straja.remedy.fix_retry", "Estimated hours must be between 0 and 24."),
    "Riscul trebuie să fie între 0 și 10.": ("straja.mission.tpl_risk",
        "straja.remedy.fix_retry", "Risk must be between 0 and 10."),
    "Participanții plătiți trebuie să fie între 1 și %s.": ("straja.mission.tpl_max_paid",
        "straja.remedy.fix_retry", "Paid participants must be between 1 and %s."),
    "Termenul trebuie să fie între %s și %s minute.": ("straja.mission.tpl_deadline",
        "straja.remedy.fix_retry", "The deadline must be between %s and %s minutes."),
    "Obiectivul trebuie să aibă 1-%s caractere.": ("straja.mission.tpl_objective",
        "straja.remedy.fix_retry", "The objective must be 1-%s characters."),
    # --- PrisonService cell geometry helper returns ---------------------------------
    "Interiorul celulei este prea mic pentru o celulă sigură.": ("straja.prison.cell_too_small",
        "straja.remedy.fix_retry", "The cell interior is too small for a safe cell."),
    "Celula depășește limitele sigure de dimensiune sau volum.": ("straja.prison.cell_too_large",
        "straja.remedy.fix_retry", "The cell exceeds safe size or volume limits."),
    "Un bloc din zona celulei nu poate fi citit; celula nu a fost creată.": ("straja.prison.cell_unreadable",
        "straja.remedy.retry", "A block in the cell area cannot be read; the cell was not created."),
    "Pereții celulei nu sunt închiși complet.": ("straja.prison.cell_open_wall",
        "straja.remedy.fix_retry", "The cell walls are not fully closed."),
    "Celula trebuie să aibă exact o ușă standard de două blocuri.": ("straja.prison.cell_door",
        "straja.remedy.fix_retry", "The cell must have exactly one standard two-block door."),
    "Celula trebuie să aibă o ușă.": ("straja.prison.cell_door_missing",
        "straja.remedy.fix_retry", "The cell must have a door."),
    # --- AdminToolService ------------------------------------------------------------
    "Traseul a atins limita de %s puncte. Sneak + click pe aer pentru finalizare.": ("straja.admintool.route_limit",
        "straja.remedy.fix_retry", "The route reached its limit of %s points. Sneak + click on air to finish."),
    "Toate locațiile administrative sunt deja configurate.": ("straja.admintool.locations_done",
        "straja.remedy.fix_retry", "All administrative locations are already configured."),
    "Nicio poziție de măsurare — click un bloc cu jalonul mai întâi.": ("straja.admintool.no_survey",
        "straja.remedy.fix_retry", "No measurement position — click a block with the marker first."),
    "Poziția măsurată este în altă dimensiune (%s).": ("straja.admintool.survey_dimension",
        "straja.remedy.fix_retry", "The measured position is in another dimension (%s)."),
    "Selectează întâi cele două colțuri ale celulei cu marcajul.": ("straja.admintool.select_corners",
        "straja.remedy.fix_retry", "Select the cell's two corners with the marker first."),
    "Celula selectată este în altă dimensiune (%s).": ("straja.admintool.cell_dimension",
        "straja.remedy.fix_retry", "The selected cell is in another dimension (%s)."),
    "Niciun șablon capturat — click un NPC Straja mai întâi.": ("straja.admintool.no_template",
        "straja.remedy.fix_retry", "No template captured — click a Straja NPC first."),
    "Poziția de clonare este în altă dimensiune (%s).": ("straja.admintool.clone_dimension",
        "straja.remedy.fix_retry", "The clone position is in another dimension (%s)."),
    "Niciun șablon de șters.": ("straja.admintool.nothing_to_clear",
        "straja.remedy.fix_retry", "No template to delete."),
    # --- NpcCommands ------------------------------------------------------------------
    "Provider necunoscut. Valori valide: customnpcs, debug-text.": ("straja.npc.provider_unknown",
        "straja.remedy.fix_retry", "Unknown provider. Valid values: customnpcs, debug-text."),
    "Legarea CustomNPCs a eșuat: %s": ("straja.npc.binding_failed",
        "straja.remedy.retry", "CustomNPCs binding failed: %s"),
    "Toate NPC-urile Straja sunt deja înregistrate.": ("straja.npc.all_registered",
        "straja.remedy.fix_retry", "All Straja NPCs are already registered."),
    # --- StrajaCommands parse helpers ----------------------------------------------------
})
'''

src = io.open(PATH, encoding="utf-8").read()
if MARKER in src:
    print("already applied")
    sys.exit(0)
io.open(PATH, "w", encoding="utf-8", newline="\n").write(src.rstrip() + "\n" + ADDITIONS)
print("appended", ADDITIONS.count('("straja.'), "entries")
